// Generated by CoffeeScript 1.6.2
(function() {
  var addAnswer, addQuestion, controller, ender, insertStuff, iteration, questions, submit, sumCorrect, validator;

  questions = [
    {
      question: "Who is Prime Minister of the United Kingdom?",
      choices: ["David Cameron", "Gordon Brown", "Winston Churchill", "Tony Blair"],
      correctAnswer: 0
    }, {
      question: "Which country has the most desert landmass?",
      choices: ["Sahara", "Chile", "Russia"],
      correctAnswer: 2
    }, {
      question: "What year did the USA land a person on the moon?",
      choices: ["IT WAS A HOAX", "1967", "1969"],
      correctAnswer: 2
    }, {
      question: "How many drugs did the Beatles consume?",
      choices: ["The Beatles were drug-free", "All the drugs", "Soft drugs like marijuana"],
      correctAnswer: 1
    }, {
      question: "What is the average velocity of an African swallow?",
      choices: ["Your father smells of elderberries", "32mph", "I will destroy you"],
      correctAnswer: 0
    }, {
      question: "Do you like bicycles?",
      choices: ["No", "They're okay", "Are there things besides bicycles?"],
      correctAnswer: 2
    }
  ];

  iteration = 0;

  sumCorrect = 0;

  addQuestion = function(question) {
    var question_el;

    question_el = document.getElementById("question");
    return question_el.innerHTML = '<h2>Question #' + (iteration + 1) + '</h2><p class="question">' + question + '</p>';
  };

  addAnswer = function(choice, answer) {
    var input, label;

    input = document.getElementById(choice);
    label = document.getElementById("label_" + choice);
    label.innerHTML = answer;
    return input.value = answer;
  };

  insertStuff = function() {
    if (questions[iteration] === void 0) {
      return ender();
    } else {
      addQuestion(questions[iteration].question);
      addAnswer("a", questions[iteration].choices[0]);
      addAnswer("b", questions[iteration].choices[1]);
      return addAnswer("c", questions[iteration].choices[2]);
    }
  };

  validator = function() {
    var chosen_answer, correct_answer, form, i, radios, _i, _ref;

    chosen_answer = null;
    correct_answer = questions[iteration].correctAnswer;
    form = document.getElementById("fieldset");
    radios = form.getElementsByTagName("input");
    for (i = _i = 0, _ref = radios.length - 1; _i <= _ref; i = _i += 1) {
      if (radios[i].checked) {
        chosen_answer = i;
        radios[i].checked = false;
        break;
      } else {
        i++;
      }
    }
    return chosen_answer;
  };

  controller = function() {
    var answer, callback, correct_answer, result_el;

    correct_answer = questions[iteration].correctAnswer;
    result_el = document.getElementById('result');
    answer = validator();
    if (answer === null) {
      result_el.innerHTML = '<p style="color:red">GIVE AN ANSWER YOU DUMMY</p>';
      callback = function() {
        return result_el.innerHTML = '';
      };
      return setTimeout(callback, 2500);
    } else {
      if (answer === correct_answer) {
        result_el.innerHTML = '<p style="color:green">Correct!</p>';
        callback = function() {
          result_el.innerHTML = '';
          sumCorrect += 1;
          iteration += 1;
          return insertStuff();
        };
        return setTimeout(callback, 1500);
      } else {
        result_el.innerHTML = '<p style="color:red">Sorry, incorrect!</p>';
        callback = function() {
          result_el.innerHTML = '';
          iteration += 1;
          return insertStuff();
        };
        return setTimeout(callback, 1500);
      }
    }
  };

  ender = function() {
    var content, playerStatus;

    content = document.getElementById('content');
    playerStatus = 'horrible';
    return content.innerHTML = '<h2>You got ' + sumCorrect + '/' + iteration + ' correct.</h2>' + '<h4>You are a ' + playerStatus + ' person.</h4>' + '<p><a href="mailto:polyrhythm@gmail.com">Fuck you</a></p>';
  };

  insertStuff();

  submit = document.getElementById('submit');

  submit.onclick = function() {
    return controller();
  };

}).call(this);
